spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_system
    username: root
    password: Testowy1
  jpa:
    # Showing sql for easier
    show-sql: true
    properties:
      hibernate:
        format:
          sql: true

# Custom properties
jwt:
  secret:
    key: "U+pamSKQ1pwTziF5t0gKCv9m8J8Y4VbW/8s0BAP6Va0="